export const canbanData = [
  {
    id: 10,
    name: "Taklif qinindi",
    color: "#eaefed",
    canbans: [
      {
        id: 32,
        project_name: "er",
        phone_number: "+998977236054",
        client_name: "ewqewq213",
        date: "1746385200000",
        cost: 2112,
        order: 0,
        description: "werrrwer",
        current_rate: 7000,
        sales_agent: {
          id: 3,
          fullname: "Muzaffarxon Abdusalomov",
          email: "asad@gmail.com",
          phone_number: "+998913231111",
          address: "Tashkent",
          telegram: "@Muzaffarxon_Dev",
          experience: "0",
        },
        currency: {
          id: 8,
          name: "RUB",
          rate: 7000,
        },
      },
    ],
    total: [
      {
        currency: "RUB",
        total_cost: "2112",
      },
    ],
  },
  {
    id: 11,
    name: "abdulaziz",
    color: "#51ba2d",
    canbans: [
      {
        id: 31,
        project_name: "zss",
        phone_number: "+998977236032",
        client_name: "ewqewqe2132",
        date: "1746471600000",
        cost: 222,
        order: 0,
        description: "ewqewq",
        current_rate: 7000,
        sales_agent: {
          id: 3,
          fullname: "Muzaffarxon Abdusalomov",
          email: "asad@gmail.com",
          phone_number: "+998913231111",
          address: "Tashkent",
          telegram: "@Muzaffarxon_Dev",
          experience: "0",
        },
        currency: {
          id: 8,
          name: "RUB",
          rate: 7000,
        },
      },
      {
        id: 33,
        project_name: "dasfqw 21",
        phone_number: "+998977236032",
        client_name: "ewqewqe2132",
        date: "1746471600000",
        cost: 222,
        order: 0,
        description: "ewqewq",
        current_rate: 7000,
        sales_agent: {
          id: 3,
          fullname: "Muzaffarxon Abdusalomov",
          email: "asad@gmail.com",
          phone_number: "+998913231111",
          address: "Tashkent",
          telegram: "@Muzaffarxon_Dev",
          experience: "0",
        },
        currency: {
          id: 8,
          name: "RUB",
          rate: 7000,
        },
      },
    ],
    total: [
      {
        currency: "RUB",
        total_cost: "222",
      },
    ],
  },
];
